### ISSUE TITLE
Data Reliability

### ISSUE THREAD

**Issue by arthurfiorette** [Bastian/bstats-backend#2]
I'm creating a multi-server project like this, but for other purposes, and when I was analyzing the http requests from the plug-ins to the backend, I wondered what would tell me if those requests come from a plug-in or from who uses a postman on the internet trying to mess up my data. And after a lot of research, I surrendered to looking at other open source projects, so I looked at yours and realized that you don't do any of that...

i copied the json sent to the server, set it to a single random plugin and changed the data. shutted down the server, opened my postman and sent this json:

```
https://bStats.org/submitData/bukkit

{
    "serverUUID": "8c5c4bc6-1f94-460f-9c34-677e07629866",
    "playerAmount": 7395,
    "onlineMode": 1,
    "bukkitVersion": "git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)",
    "bukkitName": "CraftBukkit",
    "javaVersion": "1.8.0_271",
    "osName": "Windows 10",
    "osArch": "amd64",
    "osVersion": "10.0",
    "coreCount": 6,
    "plugins": [
        {
            // EssCore is the random plugin
            "pluginName": "EssCore",
            "id": 2729,
            "pluginVersion": "1.1.0",
            "customCharts": []
        }
    ]
}
```

And as you can see here (https://prnt.sc/xddqlx) it worked. 

I remembered several times that friends asked me if a developer was good and some showed me their bstats graphics with a supposed incongruity of the data looking like the print. I'm not saying that anyone has done this before, but it would be a good way to pass development reliability.

I don't understand authentication models very well or even if it is possible to detect a server or not, but I would try to find a way, as it would be very bad for a project of this level to have untrusted data.

**Comment by Bastian** [comment]
> or even if it is possible to detect a server or not

It's not possible to distinguish between a request coming from a server and one that's coming from any other source (e.g. Postman).

The only option to "fight" this problem is by filtering out unplausible data and ratelimit incoming requests. E.g. one can safely assume that a single Bukkit server does not have more than 200 players online simultaneously, so if a request contains over 200 players, you can either completely drop it or just set the player amount to 200 (even if the request sent more).

You can see bStats' implementation here:
https://github.com/Bastian/bstats-backend/blob/8561d50752f0d27307512f165bd0beaf532cc891/src/data-submission/data-processors/single-line-chart-data.processor.ts#L25-L33

Additionally, it's also necessary to ratelimit requests per IP. Otherwise an attacker could just send thousands of requests with 200 players each. However, because of Bungeecord networks, you must assume that there can be more than 1 legitimate request per ip.

Please note, that this only applies for public services like bStats. In a closed environment, you can ofc add some kind of secret/authentication to your requests.

**Comment by Bastian** [comment]
I hope this answered the question. Feel free to respond to this issue if I should re-open it. :-)
